spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  # opcional: deixa o Swagger em /swagger
  swagger-ui:
    path: /swagger

# qualidade de vida (remove warning)
spring:
  jpa:
    open-in-view: false
